spring:
  jpa:
    properties:
      hibernate:
        format_sql: 'FALSE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
    defer-datasource-initialization: true
  mvc:
    hidden-method:
      filter:
        enabled: 'true'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${db_username}
    password: ${db_password}
    url: jdbc:mysql://localhost:3306/cozy_pets_hotel?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
  sql:
    init:
      mode: never
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: 8080
bookings:
  api:
    baseUrl: "http://localhost:8081"

