spring:
  application:
    name: cozy_pets_hotel
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'FALSE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
    defer-datasource-initialization: true
  mvc:
    hidden-method:
      filter:
        enabled: 'true'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cozy_pets_hotel?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${db_username}
    password: ${db_password}
  sql:
    init:
      mode: never
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
        transaction: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: 8080
bookings:
  api:
    baseUrl: "${BOOKINGS_BASE_URL:http://localhost:8081}"

jwt:
  secret: ${JWT_KEY:ntPHxykAkDpPDR1K3lMEkAaWzAwP0nFSThiASB}
  expiration:  ${JWT_EXPIRATION:60000}

