services:
  db:
    image: mysql
    ports:
      - "3307:3306"
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin' ]
    environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    networks:
      - pets-hotel
  cozy-pets-hotel:
    depends_on:
      - db
    image: mileneangelova/cozy-pets-hotel:v1
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1221
      - BOOKINGS_BASE_URL=http://bookings:8081
      - JWT_KEY=ntPHxykAkDpPDR1K3lMEkAaWzAwP0nFSThiASB
      - JWT_EXPIRATION=60000
    networks:
     - pets-hotel
  cozy-pets-bookings:
    depends_on: [cozy-pets-hotel]
    image: mileneangelova/cozy-pets-bookings:v1
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1221
    networks:
      - pets-hotel
networks:
  pets-hotel:
    external: true